server:
  port: 18080

spring:
  profiles:
    default: local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(hMwRR/LlukAYq6ngnyYY1ruHDLI+SLEW0Bo+Xc7G5MELZMqWCEta2Mv/TXgZXWtWy1KGFJjKiMYbFXgAc1ehqYZ3q9jv1cqWoIl1fPqRZKfhHFBFHfbpicJsG4IpAdG4Uc38tHyrnCcQh8ASBawOZtxPVf4CLxqKz/NHbAljHoMstISax8DX9ABlcgMNew2o)
    username: ENC(I+40kw10AihrqhobYVXSAQ==)
    password: ENC(NNU0SLX5fLZur9Njw+MrOQ==)


